// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKJtylwQ14m1IZ3jxuFOXmTy3Sm3x_QPk',
    appId: '1:123908719816:web:a785326bb571cbdf9551fd',
    messagingSenderId: '123908719816',
    projectId: 'websocketapp-8cad1',
    authDomain: 'websocketapp-8cad1.firebaseapp.com',
    storageBucket: 'websocketapp-8cad1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6NQ3zZz1OwUCbd_n_26mseAMCkTdXpRI',
    appId: '1:123908719816:android:104c387398f8b0479551fd',
    messagingSenderId: '123908719816',
    projectId: 'websocketapp-8cad1',
    storageBucket: 'websocketapp-8cad1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJymur-YyQa-5IvM0TkbBcWviqP4XJKo0',
    appId: '1:123908719816:ios:b1dbadd88006fb699551fd',
    messagingSenderId: '123908719816',
    projectId: 'websocketapp-8cad1',
    storageBucket: 'websocketapp-8cad1.appspot.com',
    iosBundleId: 'com.example.websocketayna',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKJtylwQ14m1IZ3jxuFOXmTy3Sm3x_QPk',
    appId: '1:123908719816:web:0dfee5e972f6ef799551fd',
    messagingSenderId: '123908719816',
    projectId: 'websocketapp-8cad1',
    authDomain: 'websocketapp-8cad1.firebaseapp.com',
    storageBucket: 'websocketapp-8cad1.appspot.com',
  );
}
